export const WEBSOCKET_RECEIVED_MESSAGE = {
    WEBSOCKET_CONNECTED_MSG: "CONNECTED",
    WEBSOCKET_DISCONNECTED_MSG: "DISCONNECTED",

    RULE_TABLE_MSG: "RULE_TABLE",
};

export const WEBSOCKET_MESSAGE_STRUCTURE = {
    command: "string",
    data: "object",
};
