name: ESLint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install ESLint
        run: npm install eslint@8.10.0 @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npx eslint . --ext .js --config .eslintrc.json
